apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashbord
spec:
  selector:
    matchLabels:
      app: arane-dash
  template:
    metadata:
      labels:
        app: arane-dash
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          image: registry.uniproject.jp/hp-infra/arane-dash:1.0.0-alpha.3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: zip
              mountPath: /nextjs/public/files
          envFrom:
            - secretRef:
                name: dashboard
      volumes:
        - name: zip
          persistentVolumeClaim:
            claimName: zip-dash
      imagePullSecrets:
        - name: internal-harbor
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: arane-dash
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
