apiVersion: v1
kind: PersistentVolume
metadata:
  name: arane-dash-zips
  labels:
    app: arane
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.unipro.infra
    path: /nfs/users/yuito-it/arane/zips
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: arane-site
    name: zip-dash

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zip-dash
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: arane-dash-zips
  selector:
    matchLabels:
      app: arane-dashboard
